networks:
  default:
    name: xoxxox_netmid
    external: true
services:
  xoxxox_appact:
    image: xoxxox_imgweb:001
    container_name: xoxxox_appact
    volumes:
    - ../../../export:/opt/common
    env_file:
    - ./envdir.txt
    command: "python /opt/common/bin/xoxxox/sndact.py"
  xoxxox_appfce:
    image: xoxxox_imgrcg:001
    container_name: xoxxox_appfce
    volumes:
    - ../../../export:/opt/common
    env_file:
    - ./envdir.txt
    command: "python /opt/common/bin/xoxxox/sndfce.py"
